#!/usr/bin/env bash
# 既存のSQLiteのデータを、PostgreSQLに移す(データだけ。テーブルは、先にバックエンドをPostgreSQLで一度起動して、Flywayに作らせておく)。
#
# 使い方:
#   PSQL="psql -h localhost -U raisechat -d raisechat" backend/scripts/migrate-sqlite-to-postgres.sh backend/raisechat.db
#
# - 移行先のテーブルは、空であること(空でなければ、何も変更せずに止まる)
# - 全体を1つのトランザクションで実行する(途中で失敗したら、PostgreSQLには何も残らない)
# - IDはそのまま引き継ぎ、連番の続きは、最大のIDの次から始まるように直す
# - 添付ファイル(uploads/)は移さない(同じ場所を使うか、S3へ移す)
# 必要なもの: sqlite3、psql(PSQL 変数でコマンドを指定する。DockerのPostgreSQLなら PSQL="docker exec -i コンテナ名 psql -U ユーザー -d DB名")
set -euo pipefail

SQLITE_DB="${1:?使い方: PSQL=\"psql ...\" $0 <SQLiteのファイル>}"
PSQL="${PSQL:?環境変数 PSQL に、psqlのコマンドを指定してください(例: PSQL=\"psql -h localhost -U raisechat -d raisechat\")}"
[ -f "$SQLITE_DB" ] || { echo "SQLiteのファイルがない: $SQLITE_DB" >&2; exit 1; }

# 移行先が空かを確認する
NOT_EMPTY=$($PSQL -At -c "select count(*) from users" 2>/dev/null || echo "ERR")
if [ "$NOT_EMPTY" = "ERR" ]; then
  echo "PostgreSQLに繋がらない、またはテーブルがない。先にバックエンドをPostgreSQLで一度起動して、テーブルを作ってください。" >&2
  exit 1
fi
if [ "$NOT_EMPTY" != "0" ]; then
  echo "移行先に、すでにユーザーが${NOT_EMPTY}人いる。空のDBに移してください(何も変更していない)。" >&2
  exit 1
fi

# テーブル名:列(外部キーの順に並べる)。reactions は id を持ち越さず、押された順(id順)に挿入して、番号を振り直す
TABLES=(
  "users:id,username,password_hash,display_name,status,avatar_url:id"
  "workspaces:id,name,owner_id:id"
  "workspace_members:workspace_id,user_id:workspace_id,user_id"
  "channels:id,workspace_id,name,is_private,is_dm:id"
  "channel_members:channel_id,user_id,last_read_message_id:channel_id,user_id"
  "messages:id,channel_id,user_id,parent_id,content,attachment_url,attachment_type,created_at,edited_at,deleted:id"
  "reactions:message_id,user_id,emoji:id"
  "mentions:message_id,user_id:message_id,user_id"
)
# 連番(IDを持ち越すテーブル)
IDENTITY=(users workspaces channels messages)

{
  echo "BEGIN;"
  # IDをそのまま入れるため、連番を一時的に「指定可」にする
  for t in "${IDENTITY[@]}"; do echo "ALTER TABLE $t ALTER COLUMN id SET GENERATED BY DEFAULT;"; done
  for spec in "${TABLES[@]}"; do
    IFS=: read -r table cols order <<<"$spec"
    # .mode insert は、文字列の引用(' の重ね書き)や NULL を、SQLとして正しい形で出力する
    sqlite3 "$SQLITE_DB" ".headers on" ".mode insert $table" "SELECT $cols FROM $table ORDER BY $order;"
  done
  for t in "${IDENTITY[@]}"; do
    echo "ALTER TABLE $t ALTER COLUMN id SET GENERATED ALWAYS;"
    # 連番の続きを、最大のIDの次にする
    echo "SELECT setval(pg_get_serial_sequence('$t', 'id'), COALESCE((SELECT MAX(id) FROM $t), 0) + 1, false);"
  done
  echo "COMMIT;"
} | $PSQL -v ON_ERROR_STOP=1 -q -o /dev/null

echo "移行した件数(SQLite → PostgreSQL):"
for spec in "${TABLES[@]}"; do
  IFS=: read -r table _ _ <<<"$spec"
  a=$(sqlite3 "$SQLITE_DB" "select count(*) from $table")
  b=$($PSQL -At -c "select count(*) from $table")
  mark="OK"; [ "$a" = "$b" ] || mark="不一致!"
  printf '  %-18s %6s → %-6s %s\n' "$table" "$a" "$b" "$mark"
done
